### ISSUE TITLE
Add French translation

### ISSUE THREAD

**Issue by ITTech37** [jhonatasrm/toolbar-weather#11]
Hello !
First of all, thanks for your response on my last issue :)

I have an other idea to improve your extension which is to add French translation. I can help you with that because i'm French.

Thanks :)

**Comment by jhonatasrm** [comment]
Hello!
>  First of all, thanks for your response on my last issue :)

You are welcome. 🙂

Please, feel free to translate, if you have some time to do that. It will be a pleasure to add a translation to French.

You just need to create a folder inside the folder "_locales" with the name "fr" and translate [messages.json](https://github.com/jhonatasrm/toolbar-weather/blob/master/src/_locales/en/messages.json).
🙂

**Comment by jhonatasrm** [comment]
Solved with the PR #13
