### ISSUE TITLE
Manual location choice

### ISSUE THREAD

**Issue by SMylk** [jhonatasrm/toolbar-weather#12]
I did not find where could i input my city, is there an option like this?

**Comment by jhonatasrm** [comment]
Hello!

> I did not find where could i input my city, is there an option like this?

Not for now... the search is made accessing your location, but it is in my plans to add this feature. I will keep this issue opened to work on that.

Thank you very much for your feedback! 🙂

**Comment by supermariobr** [comment]
Weather is showing in the wrong city...
Can you include the option for user set location manually?

**Comment by jhonatasrm** [comment]
> Weather is showing in the wrong city... Can you include the option for user set location manually?

Hello!

I'm currently working on that, and I plan to have it finished by the weekend.

**Comment by jhonatasrm** [comment]
The new manual location feature was released today in version 2.3.1 of the Add-on. If you encounter any issues, please open a new issue.

![toolbar-weather](https://github.com/user-attachments/assets/492b9ccc-e5cf-4d3d-a493-daff1e56b6bd)

Thank you very much for your support!

**Comment by supermariobr** [comment]
Big thank you!!!

Em sáb., 19 de out. de 2024 às 16:48, Jhonatas Machado <
***@***.***> escreveu:
