### ISSUE TITLE
font in win10 large+bold...

### ISSUE THREAD

**Issue by m2c2lure67** [jhonatasrm/toolbar-weather#21]
...can't see the bottom of the drop-down

**Comment by jhonatasrm** [comment]
Hello,

Thank you very much for the information. I will take a look at that.

Best Regards,
Jhonatas

**Comment by m2c2lure67** [comment]
p.s., Are you porting this extension to Google Chrome?...

**Comment by jhonatasrm** [comment]
Yes, I was thinking in do that. Before, I need to discontinue some extensions and think about which one to port to Chrome.

But for sure this one will be there at some moment.
:)
