### ISSUE TITLE
Can't geolocate in Waterfox

### ISSUE THREAD

**Issue by cjrobe** [jhonatasrm/toolbar-weather#24]
It just shows the dancing purple dots indefinitely.

Does it depend on some Firefox functionality for geolocation that is not included in Waterfox? Manual location would be good per other request from 2020.

Thanks.

**Comment by jhonatasrm** [comment]
Hello, 

Thank you very much for opening that issue about the Waterfox browser. I did some tests here using Waterfox with the website [https://browserleaks.com/geo](https://browserleaks.com/geo) to test the geolocation API, and he is returning an error to determine the position.

![print_waterfox_geolocationAPI](https://user-images.githubusercontent.com/8497721/187044372-c23ba0c9-3152-4092-96a9-abec8007a0e7.png)


Testing in other browsers the error mentioned above didn't happen, I will take a look at some workarounds for that. Your suggestion is great, I'm thinking in work with fields to put the Latitude and Longitude, once is about all over the world geolocations and demanding a lot of APIs to Country, State, City... 

Best Regards,
Jhonatas
