### ISSUE TITLE
Background color behind temp

### ISSUE THREAD

**Issue by skstudi0** [jhonatasrm/toolbar-weather#4]
Is there currently any way to change the background color behind the temp window or add in a color picker for it in a future update? The blue/black combo is a bit hard to read for me. 
![tempbackground](https://user-images.githubusercontent.com/50462179/57478168-47e70b00-7268-11e9-90c8-97a4ca0677c6.JPG)

**Comment by jhonatasrm** [comment]
It is an excellent idea for an upcoming update...I want work more in the interface and this will be a great addition.
I'm thinking in put a picker to choose both colors (background and font).

Thank you for your suggestion!

**Comment by jhonatasrm** [comment]
Feature implemented in version 2.0.1 😃
