### ISSUE TITLE
Feature Request - Refresh button and/or set refresh interval

### ISSUE THREAD

**Issue by ITTech37** [jhonatasrm/toolbar-weather#9]
Implement a refresh button in the GUI and if possible, a setting to control the refresh interval.
Thanks.

**Comment by jhonatasrm** [comment]
If you open a new tab and access the page 'about:addons' and the preferences of the Add-on you will be able to select the time (in minutes) to refresh the tab. 

I'm also thinking to implement a popup menu when clicked at the Add-on icon to do in a more fast way the changes in the preferences.

Thank you for your feature request!
🙂

**Comment by jhonatasrm** [comment]
Hello! 

I did some changes and fixes using your opened issue, in the future, I hope to bring more changes and enhancements to the project.

Thank you so much for your feedback, anything more, please let me know.
🙂
